name: geniozinho
description: GÃªniozinho
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+3

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  get_it: ^8.0.1
  vsync_provider: ^0.5.0
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  tuple: ^2.0.2
  fluttertoast: ^8.2.8
  figma_squircle: ^0.5.3
  audioplayers: ^6.1.0
  step_progress_indicator: ^1.0.2
  percent_indicator: ^4.2.3
  auto_size_text: ^3.0.0
  flutter_switch: ^0.3.2
  share_plus: ^10.1.1
  flutter_email_sender: ^6.0.3
  url_launcher: ^6.3.1
  device_info_plus: ^11.1.0
  flutter_rating_bar: ^4.0.1
  footer: ^0.0.4
  google_mobile_ads: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/
    - assets/images/
    - assets/imgYellow/
    - assets/imgGreen/
    - assets/imgBlue/
    - assets/imgBlueDark/
    - assets/imgGreenDark/
    - assets/imgYellowDark/
    - assets/tick.mp3
    - assets/wrong.mp3
    - assets/right.mp3
    - assets/gameover.mp3
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
    - family: OriginalSurfer
      fonts:
        - asset: assets/fonts/OriginalSurfer-Regular.ttf
          weight: 700

    - family: Latinotype
      fonts:
        - asset: assets/fonts/Latinotype - Moranga Bold.otf
          weight: 800
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
flutter_intl:
  enabled: true