name: geniozinho
description: GÃªniozinho
publish_to: "none"
version: 3.1.6+10

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  flutter_svg: ^2.0.17
  vsync_provider: ^0.5.0
  provider: ^6.1.5
  shared_preferences: ^2.5.4
  tuple: ^2.0.2
  fluttertoast: ^9.0.0
  figma_squircle: ^0.6.3
  audioplayers: ^6.4.0
  step_progress_indicator: ^1.0.2
  percent_indicator: ^4.2.4
  auto_size_text: ^3.0.0
  flutter_switch: ^0.3.2
  share_plus: ^11.1.0
  flutter_email_sender: ^8.0.0
  url_launcher: ^6.3.2
  device_info_plus: ^12.3.0
  flutter_rating_bar: ^4.0.1
  footer: ^0.0.4
  google_mobile_ads: ^7.0.0
  firebase_analytics: ^12.1.0
  firebase_crashlytics: ^5.0.6
  get_it: ^9.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3
  intl_utils: ^2.8.13

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/imgYellow/
    - assets/imgGreen/
    - assets/imgBlue/
    - assets/imgBlueDark/
    - assets/imgGreenDark/
    - assets/imgYellowDark/
    - assets/tick.mp3
    - assets/wrong.mp3
    - assets/right.mp3
    - assets/gameover.mp3
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
    - family: OriginalSurfer
      fonts:
        - asset: assets/fonts/OriginalSurfer-Regular.ttf
          weight: 700

    - family: Latinotype
      fonts:
        - asset: assets/fonts/Latinotype - Moranga Bold.otf
          weight: 800
flutter_intl:
  enabled: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/geniozinho_mascote.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/geniozinho_mascote.png"
